print('Hello People!')
print('Today You Will Tell Us About Yourself')
print('What is your name?')
name  = input()
print('How old are you?')
age = int(input())
print('Where do you live?')
location = input()
print('Do you believe people are funny?\n Type 1. Yes or yes 2. No or no')
reply = int(input())
if reply == 1:
 print('I agreee!')
elif reply == 2:
 print('Ah Well?')
print('Thanks for taking the time to answer \n these questions')
